version: '2'
services:
  db:
    image: postgres
  dev:
    image: ditsara/devenv-ruby
    build: .
    volumes:
      - ./user:/home/user
      - ./development:/home/development
    depends_on:
      - db

